server:
  port: 8081

spring:
  application:
    name: catalog-service
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  datasource:
    url: jdbc:postgresql://localhost/store
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        default_schema: catalog
        id:
          new_generator_mappings: false
        temp:
          use_jdbc_metadata_defaults: false
  main:
    allow-bean-definition-overriding: true

rabbit:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchange: rabbit.exchange
    accountingQueue: rabbit.accountingQueue
    catalogQueue: rabbit.catalogQueue
    confirmationKey: rabbit.confirmationKey
    cancellingKey: rabbit.cancellingKey
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

